include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    unused_catch_clause: ignore ignore ignore ignore
    use_build_context_synchronously: ignore
